# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aleksey/module/firmware_module

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aleksey/module/firmware_module

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aleksey/module/firmware_module/CMakeFiles /home/aleksey/module/firmware_module/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aleksey/module/firmware_module/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named firmware-module

# Build rule for target.
firmware-module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 firmware-module
.PHONY : firmware-module

# fast build rule for target.
firmware-module/fast:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/build
.PHONY : firmware-module/fast

armc-cstartup.obj: armc-cstartup.c.obj

.PHONY : armc-cstartup.obj

# target to build an object file
armc-cstartup.c.obj:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/armc-cstartup.c.obj
.PHONY : armc-cstartup.c.obj

armc-cstartup.i: armc-cstartup.c.i

.PHONY : armc-cstartup.i

# target to preprocess a source file
armc-cstartup.c.i:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/armc-cstartup.c.i
.PHONY : armc-cstartup.c.i

armc-cstartup.s: armc-cstartup.c.s

.PHONY : armc-cstartup.s

# target to generate assembly for a file
armc-cstartup.c.s:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/armc-cstartup.c.s
.PHONY : armc-cstartup.c.s

armc-cstubs.obj: armc-cstubs.c.obj

.PHONY : armc-cstubs.obj

# target to build an object file
armc-cstubs.c.obj:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/armc-cstubs.c.obj
.PHONY : armc-cstubs.c.obj

armc-cstubs.i: armc-cstubs.c.i

.PHONY : armc-cstubs.i

# target to preprocess a source file
armc-cstubs.c.i:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/armc-cstubs.c.i
.PHONY : armc-cstubs.c.i

armc-cstubs.s: armc-cstubs.c.s

.PHONY : armc-cstubs.s

# target to generate assembly for a file
armc-cstubs.c.s:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/armc-cstubs.c.s
.PHONY : armc-cstubs.c.s

armc-start.obj: armc-start.S.obj

.PHONY : armc-start.obj

# target to build an object file
armc-start.S.obj:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/armc-start.S.obj
.PHONY : armc-start.S.obj

firmware.obj: firmware.c.obj

.PHONY : firmware.obj

# target to build an object file
firmware.c.obj:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/firmware.c.obj
.PHONY : firmware.c.obj

firmware.i: firmware.c.i

.PHONY : firmware.i

# target to preprocess a source file
firmware.c.i:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/firmware.c.i
.PHONY : firmware.c.i

firmware.s: firmware.c.s

.PHONY : firmware.s

# target to generate assembly for a file
firmware.c.s:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/firmware.c.s
.PHONY : firmware.c.s

peripheral/lls/nmcload.obj: peripheral/lls/nmcload.c.obj

.PHONY : peripheral/lls/nmcload.obj

# target to build an object file
peripheral/lls/nmcload.c.obj:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/lls/nmcload.c.obj
.PHONY : peripheral/lls/nmcload.c.obj

peripheral/lls/nmcload.i: peripheral/lls/nmcload.c.i

.PHONY : peripheral/lls/nmcload.i

# target to preprocess a source file
peripheral/lls/nmcload.c.i:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/lls/nmcload.c.i
.PHONY : peripheral/lls/nmcload.c.i

peripheral/lls/nmcload.s: peripheral/lls/nmcload.c.s

.PHONY : peripheral/lls/nmcload.s

# target to generate assembly for a file
peripheral/lls/nmcload.c.s:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/lls/nmcload.c.s
.PHONY : peripheral/lls/nmcload.c.s

peripheral/module-gpio.obj: peripheral/module-gpio.c.obj

.PHONY : peripheral/module-gpio.obj

# target to build an object file
peripheral/module-gpio.c.obj:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-gpio.c.obj
.PHONY : peripheral/module-gpio.c.obj

peripheral/module-gpio.i: peripheral/module-gpio.c.i

.PHONY : peripheral/module-gpio.i

# target to preprocess a source file
peripheral/module-gpio.c.i:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-gpio.c.i
.PHONY : peripheral/module-gpio.c.i

peripheral/module-gpio.s: peripheral/module-gpio.c.s

.PHONY : peripheral/module-gpio.s

# target to generate assembly for a file
peripheral/module-gpio.c.s:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-gpio.c.s
.PHONY : peripheral/module-gpio.c.s

peripheral/module-systimer.obj: peripheral/module-systimer.c.obj

.PHONY : peripheral/module-systimer.obj

# target to build an object file
peripheral/module-systimer.c.obj:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-systimer.c.obj
.PHONY : peripheral/module-systimer.c.obj

peripheral/module-systimer.i: peripheral/module-systimer.c.i

.PHONY : peripheral/module-systimer.i

# target to preprocess a source file
peripheral/module-systimer.c.i:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-systimer.c.i
.PHONY : peripheral/module-systimer.c.i

peripheral/module-systimer.s: peripheral/module-systimer.c.s

.PHONY : peripheral/module-systimer.s

# target to generate assembly for a file
peripheral/module-systimer.c.s:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-systimer.c.s
.PHONY : peripheral/module-systimer.c.s

peripheral/module-uart.obj: peripheral/module-uart.c.obj

.PHONY : peripheral/module-uart.obj

# target to build an object file
peripheral/module-uart.c.obj:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-uart.c.obj
.PHONY : peripheral/module-uart.c.obj

peripheral/module-uart.i: peripheral/module-uart.c.i

.PHONY : peripheral/module-uart.i

# target to preprocess a source file
peripheral/module-uart.c.i:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-uart.c.i
.PHONY : peripheral/module-uart.c.i

peripheral/module-uart.s: peripheral/module-uart.c.s

.PHONY : peripheral/module-uart.s

# target to generate assembly for a file
peripheral/module-uart.c.s:
	$(MAKE) -f CMakeFiles/firmware-module.dir/build.make CMakeFiles/firmware-module.dir/peripheral/module-uart.c.s
.PHONY : peripheral/module-uart.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... firmware-module"
	@echo "... armc-cstartup.obj"
	@echo "... armc-cstartup.i"
	@echo "... armc-cstartup.s"
	@echo "... armc-cstubs.obj"
	@echo "... armc-cstubs.i"
	@echo "... armc-cstubs.s"
	@echo "... armc-start.obj"
	@echo "... firmware.obj"
	@echo "... firmware.i"
	@echo "... firmware.s"
	@echo "... peripheral/lls/nmcload.obj"
	@echo "... peripheral/lls/nmcload.i"
	@echo "... peripheral/lls/nmcload.s"
	@echo "... peripheral/module-gpio.obj"
	@echo "... peripheral/module-gpio.i"
	@echo "... peripheral/module-gpio.s"
	@echo "... peripheral/module-systimer.obj"
	@echo "... peripheral/module-systimer.i"
	@echo "... peripheral/module-systimer.s"
	@echo "... peripheral/module-uart.obj"
	@echo "... peripheral/module-uart.i"
	@echo "... peripheral/module-uart.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

